name: using hello custom action

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: using custom actions
              uses: ./
              with:
                  who-to-greet: "coderco team"
